---
title: "Perceptions of Perfectionism in the Public Domain: a Sentiment Analsyis"
output: "html_document"
---
***
##### **What is the problem you want to solve?**
Recent meta-analytical evidence has demonstrated that levels of perfectionism in Western populations has linearly increased over the past three decades, largely in part due to an increase in neoliberal governance in the US, Canada, and the UK that emphasizes competitive individualism. Over this time period, evidence has also broadly indicated perfectionism to be a personality trait fraught with negative outcomes, processes, and characteristics (although some researchers maintain there also exists some positive outcomes, processes, and characteristics).

Despite a growing body of literature, little is known about public perceptions of perfectionism in terms of how people are talking and feel about perfectionism (i.e., whether it is perceived to be a positive or negative construct). This remains an issue as in order for academics to *effectively* disseminate their research to a broader audience, including the public domain (e.g., through news and media outlets), the framework through which perfectionism is perceived must be *better* understood.

***

##### **Who is your client and why do they care about this problem? In other words, what will your client DO or DECIDE based on your analysis that they wouldn’t have otherwise?**
The primary client for this project is the MPaW (Motivation, Performance, and Wellbeing) reserch group, which consists of researchers across the University of Bath, York St John University, and Leeds Becket University. The MPaW group is one of the worlds leading groups investigating perfectionism.

Professor Andy Hill, lead of the the MPaW group, has already demonstrated interest in this project:

> "Sounds like a really interesting project. An assessment of the meaning and social understanding of perfectionism (inferred by the other words/topics it coalesces with) and if this has changed over time, would contribute to research in this area. I look forward to seeing the results!"

The results of this project will be used by the MPaW group for two key purposes:

1. Assist in the tranlsation and disseminaton of results from academic research papers into the public domain, in a manner that is digestable and challenges any preconceived biases and perceptions. This is important too for the University institutions, as part of their resarch funding is achieved through the REF system, of which they are graded for *effective* dissemination of their research findings into the borader public domain.
2. Assist in the development of psychometric instruments (of which are undeprinned by question wording and perception).

***

##### **What data are you going to use for this? How will you acquire this data?**

Data will be scraped from news and blog sites using a variety of appraoches: (i) where possible, API clients will be used to scrape data, (ii) the {Rcrawler} package will be used to crawl sites using xPath and keyword queries (iii) the {rvest} package will be used to scrape data by iterating through a list of provided URL's, (iv) the {tm.plugin.webmining} package will be used to scrape data from various news platforms.

***

##### **In brief, outline your approach to solving this problem (knowing that this might change later).**

First, a semantic analysis using a tidy text approach as outlined in Silge and Robinson (2017) will be performed. This involves wrangling the data into a 'tidy' format using tidy data principles, and then using the {tidytext} package in conjunction with several tidyverse packages to explore the data. Secondly, topic modelling will be performed, using the Latent Dirichlet Allocation algorithm in conjuction with the {topicmodels} package.

***

##### **What are your deliverables? Typically, this would include code, along with a paper and/or a slide deck.**

1. R code that extracts, wrangles, and analyses the data.
2. A report, written in R Markdown, which summarises the problem, strategies, and findings.
3. A non-technical slide deck.